[build]
  command = "npm ci --legacy-peer-deps && npm run build && npm run build-storybook && mkdir -p dist/storybook && cp -r storybook-static/* dist/storybook/"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.6"
  NPM_FLAGS = "--no-optional"

[[redirects]]
  from = "/storybook/*"
  to = "/storybook/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[stackbit]
  # Website builder workflow
  build_cmd = "npm run build"
  dev_cmd = "npm run dev"
  container_port = 5173
  node_version = "18" 