[build]
  command = "npm ci && npm run build && npm run build-storybook && npm run postbuild"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.6"
  NPM_FLAGS = "--no-optional"

[[redirects]]
  from = "/storybook/*"
  to = "/storybook/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 