[build]
  command = "npm ci --legacy-peer-deps && npm run build && (npm run build-storybook || true) && mkdir -p dist/storybook && (cp -r storybook-static/* dist/storybook/ || true)"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.6"
  NPM_FLAGS = "--no-optional --legacy-peer-deps"

[[redirects]]
  from = "/storybook/*"
  to = "/storybook/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[stackbit]
  # Website builder workflow
  build_cmd = "npm run build"
  dev_cmd = "npm run dev"
  container_port = 5173
  nodeVersion = "18"
  install_cmd = "npm install --no-audit --prefer-offline --legacy-peer-deps"
  # Force Node.js 18 for all operations
  env = { NODE_VERSION = "18.20.6", NODE_ENV = "development" }

[[plugins]]
  package = "@netlify/plugin-visual-editor" 